version: "3"

vars:
  OUTPUT_PATH: "odin-out"
  OUTPUT:
    sh: basename $(pwd)

tasks:
  clean:
    cmds:
      - rm -rf {{.OUTPUT_PATH}}

  build:
    dir: "{{.OUTPUT_PATH}}"
    cmds:
      - odin build ../main.odin -file -out:main -o:speed

  run:
    dir: "{{.OUTPUT_PATH}}"
    cmd: ./main
