version: "3"

vars:
  OUTPUT_PATH: "odin-out"
  OUTPUT:
    sh: basename $(pwd)

tasks:
  clean:
    cmds:
      - rm -rf {{.OUTPUT_PATH}}

  build:
    dir: "{{.OUTPUT_PATH}}"
    cmds:
      - odin build ../main.odin -file -out:{{.OUTPUT}} -o:speed

  run:
    dir: "{{.OUTPUT_PATH}}"
    cmds:
      - silent: true
        cmd: |
          if [ -x "{{.OUTPUT}}" ]; then
            ./{{.OUTPUT}} {{.CLI_ARGS}}
          else
            odin run ../main.odin -file -out:{{.OUTPUT}} -- {{.CLI_ARGS}}
          fi