//--------------------------------------------------------------------------------
// sudo apt install libmariadb-dev libmariadb-dev-compat
//--------------------------------------------------------------------------------
package main

import "core:fmt"
//--------------------------------------------------------------------------------
//################################################################################
//--------------------------------------------------------------------------------
main :: proc() {
	//------------------------------------------------------------
	HOST :: "127.0.0.1"
	PORT: u32 = 3306
	USER :: "root"
	PASSWD :: ""
	DB: cstring = nil
	CLIENT_FLAG: u64 = CLIENT_MULTI_STATEMENTS
	//------------------------------------------------------------
	db_handle := mysql_init(nil)
	if (db_handle == nil) {
		fmt.eprint("mysql_init error")
		return
	}
	defer mysql_close(db_handle)
	//------------------------------------------------------------
	if mysql_real_connect(db_handle, HOST, USER, PASSWD, DB, PORT, nil, CLIENT_FLAG) == nil {
		fmt.eprintf("mysql_real_connect: %s\n", mysql_error(db_handle))
		return
	}
	//------------------------------------------------------------
	fmt.printf("connected to %s:%d\n", HOST, PORT)
	//------------------------------------------------------------
	{
		if mysql_query(db_handle, "SELECT VERSION();") != 0 {
			fmt.eprintf("mysql_query: %s\n", mysql_error(db_handle))
			return
		}

		result := mysql_store_result(db_handle)
		if (result == nil) {
			fmt.eprintf("mysql_store_result: %s\n", mysql_error(db_handle))
			return
		}
		defer mysql_free_result(result)

		for {
			row := mysql_fetch_row(result)
			if row == nil {
				break
			}
			if row[0] != nil {
				fmt.printf("version: %s\n", row[0])
			}
		}
	}
	//------------------------------------------------------------
	{
		sql: cstring = `CREATE DATABASE IF NOT EXISTS test;
        	USE test;
            DROP TABLE IF EXISTS cars;
            CREATE TABLE cars(id INT NOT NULL AUTO_INCREMENT, name VARCHAR(255), price INT DEFAULT 0 NOT NULL, PRIMARY KEY(id));
            INSERT INTO cars(name, price) VALUES('Skoda', 9000);
            INSERT INTO cars(name, price) VALUES('Audi', 52642);
			`

		if mysql_query(db_handle, sql) != 0 {
			fmt.eprintf("mysql_query: %s\n", mysql_error(db_handle))
			return
		}

		// consume every result generated by each line
		for {
			result := mysql_store_result(db_handle)

			if (result != nil) {
				mysql_free_result(result)
			} else if mysql_field_count(db_handle) != 0 {
				fmt.eprintf("mysql_store_result: %s\n", mysql_error(db_handle))
				return
			}

			rc := mysql_next_result(db_handle)

			if rc == 0 do continue

			if rc > 0 {
				fmt.eprintf("mysql_next_result: %s\n", mysql_error(db_handle))
				return
			}

			break
		}
	}
	//------------------------------------------------------------
	{
		if mysql_query(db_handle, "SELECT * FROM cars;") != 0 {
			fmt.eprintf("mysql_query: %s\n", mysql_error(db_handle))
			return
		}

		result := mysql_store_result(db_handle)
		if (result == nil) {
			fmt.eprintf("mysql_store_result: %s\n", mysql_error(db_handle))
			return
		}
		defer mysql_free_result(result)

		for {
			row := mysql_fetch_row(result)
			if row == nil {
				break
			}
			if row[0] != nil {
				fmt.printf("id: %s, name: %s, price: %s\n", row[0], row[1], row[2])
			}
		}
	}
	//------------------------------------------------------------
}
//--------------------------------------------------------------------------------
//################################################################################
//--------------------------------------------------------------------------------
printLine :: proc() {fmt.println(
		"--------------------------------------------------------------------------------",
	)}
//--------------------------------------------------------------------------------
//################################################################################
//--------------------------------------------------------------------------------
MYSQL :: rawptr
MYSQL_RES :: rawptr
MYSQL_ROW :: [^]cstring
//--------------------------------------------------------------------------------
CLIENT_MULTI_STATEMENTS: u64 = 1 << 16
//--------------------------------------------------------------------------------
foreign import libmysql "system:mysqlclient"
foreign libmysql {
	//------------------------------------------------------------
	mysql_close :: proc(sock: ^MYSQL) ---
	mysql_error :: proc "c" (mysql: ^MYSQL) -> cstring ---
	mysql_fetch_row :: proc "c" (result: ^MYSQL_RES) -> MYSQL_ROW ---
	mysql_field_count :: proc "c" (mysql: ^MYSQL) -> u32 ---
	mysql_free_result :: proc "c" (result: ^MYSQL_RES) ---
	mysql_init :: proc "c" (mysql: ^MYSQL) -> ^MYSQL ---
	mysql_next_result :: proc "c" (mysql: ^MYSQL) -> i32 ---
	mysql_query :: proc "c" (mysql: ^MYSQL, query: cstring) -> i32 ---
	mysql_real_connect :: proc "c" (mysql: ^MYSQL, host: cstring, user: cstring, passwd: cstring, db: cstring, port: u32, unix_socket: cstring, clientflag: u64) -> ^MYSQL ---
	mysql_store_result :: proc "c" (mysql: ^MYSQL) -> ^MYSQL_RES ---
	//------------------------------------------------------------
}
//--------------------------------------------------------------------------------
